name: Link Check

on:
  pull_request:
    branches:
      - master
      - staging
      - trying
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Check Links
        run: bash ./.github/link_check.sh

